@echo off
if not exist "c:\EDUASSIST\frontend\src\features\exams" mkdir "c:\EDUASSIST\frontend\src\features\exams"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_frontend_src_features_exams_CreateExamScreen.tsx" "c:\EDUASSIST\frontend\src\features\exams\CreateExamScreen.tsx"
if not exist "c:\EDUASSIST\frontend\app\exam" mkdir "c:\EDUASSIST\frontend\app\exam"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_frontend_app_exam__layout.tsx" "c:\EDUASSIST\frontend\app\exam\_layout.tsx"
if not exist "c:\EDUASSIST\frontend\src\features\exams" mkdir "c:\EDUASSIST\frontend\src\features\exams"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_frontend_src_features_exams_ExamResultsScreen.tsx" "c:\EDUASSIST\frontend\src\features\exams\ExamResultsScreen.tsx"
if not exist "c:\EDUASSIST\backend\resources\views\exam" mkdir "c:\EDUASSIST\backend\resources\views\exam"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_resources_views_exam_exam-compose.blade.php" "c:\EDUASSIST\backend\resources\views\exam\exam-compose.blade.php"
if not exist "c:\EDUASSIST\frontend\src\features\exams" mkdir "c:\EDUASSIST\frontend\src\features\exams"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_frontend_src_features_exams_ExamListScreen.tsx" "c:\EDUASSIST\frontend\src\features\exams\ExamListScreen.tsx"
if not exist "c:\EDUASSIST\backend\database\migrations" mkdir "c:\EDUASSIST\backend\database\migrations"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_database_migrations_2026_07_28_170000_create_exams_table.php" "c:\EDUASSIST\backend\database\migrations\2026_07_28_170000_create_exams_table.php"
if not exist "c:\EDUASSIST\backend\database\migrations" mkdir "c:\EDUASSIST\backend\database\migrations"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_database_migrations_2026_07_28_170001_create_exam_submissions_table.php" "c:\EDUASSIST\backend\database\migrations\2026_07_28_170001_create_exam_submissions_table.php"
if not exist "c:\EDUASSIST\backend\app\Models" mkdir "c:\EDUASSIST\backend\app\Models"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_app_Models_Exam.php" "c:\EDUASSIST\backend\app\Models\Exam.php"
if not exist "c:\EDUASSIST\backend\app\Models" mkdir "c:\EDUASSIST\backend\app\Models"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_app_Models_ExamSubmission.php" "c:\EDUASSIST\backend\app\Models\ExamSubmission.php"
if not exist "c:\EDUASSIST\backend\app\Services" mkdir "c:\EDUASSIST\backend\app\Services"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_app_Services_ExamCorrectionService.php" "c:\EDUASSIST\backend\app\Services\ExamCorrectionService.php"
if not exist "c:\EDUASSIST\backend\app\Http\Controllers\Exam" mkdir "c:\EDUASSIST\backend\app\Http\Controllers\Exam"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_app_Http_Controllers_Exam_ExamController.php" "c:\EDUASSIST\backend\app\Http\Controllers\Exam\ExamController.php"
if not exist "c:\EDUASSIST\backend\app\Http\Controllers\Exam" mkdir "c:\EDUASSIST\backend\app\Http\Controllers\Exam"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_app_Http_Controllers_Exam_ExamPublicController.php" "c:\EDUASSIST\backend\app\Http\Controllers\Exam\ExamPublicController.php"
if not exist "c:\EDUASSIST\backend\resources\views\exam" mkdir "c:\EDUASSIST\backend\resources\views\exam"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_resources_views_exam_exam-login.blade.php" "c:\EDUASSIST\backend\resources\views\exam\exam-login.blade.php"
if not exist "c:\EDUASSIST\backend\resources\views\exam" mkdir "c:\EDUASSIST\backend\resources\views\exam"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_resources_views_exam_exam-submitted.blade.php" "c:\EDUASSIST\backend\resources\views\exam\exam-submitted.blade.php"
if not exist "c:\EDUASSIST\backend\resources\views\exam" mkdir "c:\EDUASSIST\backend\resources\views\exam"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_backend_resources_views_exam_exam-closed.blade.php" "c:\EDUASSIST\backend\resources\views\exam\exam-closed.blade.php"
if not exist "c:\EDUASSIST\frontend\src\types" mkdir "c:\EDUASSIST\frontend\src\types"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_frontend_src_types_exam.types.ts" "c:\EDUASSIST\frontend\src\types\exam.types.ts"
if not exist "c:\EDUASSIST\frontend\src\services" mkdir "c:\EDUASSIST\frontend\src\services"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_frontend_src_services_ExamService.ts" "c:\EDUASSIST\frontend\src\services\ExamService.ts"
if not exist "c:\EDUASSIST\frontend\app\(tabs)" mkdir "c:\EDUASSIST\frontend\app\(tabs)"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_frontend_app__tabs__exams.tsx" "c:\EDUASSIST\frontend\app\(tabs)\exams.tsx"
if not exist "c:\EDUASSIST\frontend\app\exam" mkdir "c:\EDUASSIST\frontend\app\exam"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_frontend_app_exam__examId_.tsx" "c:\EDUASSIST\frontend\app\exam\[examId].tsx"
if not exist "c:\EDUASSIST\frontend\app\exam" mkdir "c:\EDUASSIST\frontend\app\exam"
copy /Y "C:\EDUASSIST\backend\scratch\exam_recovery\c__EDUASSIST_frontend_app_exam_create.tsx" "c:\EDUASSIST\frontend\app\exam\create.tsx"
